In [ ]:
# -*- coding: utf-8 -*-
"""
Created on Wed Jan 12 18:20:37 2022

@author: 18053
"""


import os
import pandas as pd
import numpy as np
import copy

df = pd.read_csv('data.tsv', sep='\t', header=None)
df.columns = ['word', 'relation', 'related_word']
df = df[df['relation'] == "rel:etymology"]

df['word'] = df['word'].apply(lambda x: x.split(': '))
df['related_word'] = df['related_word'].apply(lambda x: x.split(': '))

df['word_language'] = df['word'].apply(lambda x: x[0])
df['word'] = df['word'].apply(lambda x: x[1])

df['related_word_language'] = df['related_word'].apply(lambda x: x[0])
df['related_word'] = df['related_word'].apply(lambda x: x[1])

df = df[['word', 'word_language', 'related_word',
         'related_word_language']]

#df = df[~df['word'].str.contains('-')]

x = df[(df['word_language'] == 'eng')]
pivot = pd.pivot_table(data = x, index = 'related_word_language',
                       values='word_language',
                       aggfunc='count').sort_values('word_language', ascending=False)
# enm = middle english
# ang = old english
print(pivot.head(15))

In [ ]:
df.to_csv('small_data.csv')

In [ ]:
copy_df = copy.deepcopy(df)
copy_df.columns = ['related_word', 'related_word_language', 'word3', 'word3_language']

In [ ]:
new_df = df.merge(copy_df, on = ['related_word', 'related_word_language'], how='inner')
new_df.head()

In [ ]:
def find_root_language(word):
    print(word)
    temp = df[(df['word'] == word) & 
              ~(df['related_word'].str.contains('-')) &
               (df['word_language'] == 'eng')]
    #print(temp)
    if temp.shape[0] == 0:
        temp = df[(df['word'] == word) & (df['word_language'] == 'eng')]
        if temp.shape[0] == 0:
            return np.nan
        
    new_word, language = temp.iloc[0, 2], temp.iloc[0, 3]
    if new_word == word:
        return np.nan
    
    if language == 'eng':
        return find_root_language(new_word)
    else:
        return language

In [ ]:
english_df = df[df['word_language'] == 'eng']

In [ ]:
test_df = copy.deepcopy(english_df)

In [ ]:
english_df = english_df[~english_df['word'].str.contains('\'')]
english_df = english_df[~english_df['word'].str.contains('-')]
english_df = english_df[~english_df['word'].str.contains('\d')]
english_df = english_df[english_df['word'] <= 'zzzzzz']
english_df['word'] = english_df['word'].apply(lambda x: x.lower())

In [ ]:
import json

In [43]:
word_li = english_df['word'].values

In [67]:
english_df['origin'] = english_df['word'].apply(lambda x: word_dict[x])

In [72]:
english_df[~pd.notnull(english_df['origin'])].tail()

               word word_language related_word related_word_language origin
1338098   zymolysis           eng       -lysis                   eng    NaN
1338099   zymolysis           eng        zymo-                   eng    NaN
1338120  zymosterol           eng       sterol                   eng    NaN
1338121  zymosterol           eng        zymo-                   eng    NaN
1338142      zythum           eng       zythum                   lat    NaN

In [128]:
def find_root_language(word):
    temp = df[(df['word'] == word) &
              ~(df['related_word'].str.contains('-')) &
               (df['word_language'] == 'eng')]

    if temp.shape[0] == 0:
        temp = df[(df['word'] == word) & (df['word_language'] == 'eng')]
        if temp.shape[0] == 0:
            return None
       
    new_word, language = temp.iloc[0, 2], temp.iloc[0, 3]
    
    if new_word == word and language == 'eng':
        return None
    
    if language == 'eng':
        return find_root_language(new_word)
    else:
        return language

In [135]:
import time

In [139]:
i = 0
j = 0
for word in word_dict.keys():
    if word_dict[word] == None:
        new_lang = find_root_language(word)
        word_dict[word] = new_lang
        
        if new_lang != None:
            if i % 100 == 0 and i > 0:
                t0 = time.perf_counter()
                print('outputting to json ending with word ', word, ' number', i)
                with open("sample.json", "w") as outfile:
                    json.dump(word_dict, outfile)
                t1 = time.perf_counter()
                print(f"Outputted json in {t1 - t0:0.2f} seconds")
            i += 1
    j += 1
    if j % 1000 == 0:
            print('current word:', word, ' number:', j)

current word: chile  number: 1000
current word: hegelianism  number: 2000
outputting to json ending with word  jacobitism  number 100
Outputted json in 0.66 seconds
outputting to json ending with word  jyothis  number 200
Outputted json in 0.72 seconds
outputting to json ending with word  kulturtr√§ger  number 300
Outputted json in 0.65 seconds
outputting to json ending with word  lojbanize  number 400
Outputted json in 0.68 seconds
outputting to json ending with word  manu  number 500
Outputted json in 0.50 seconds
current word: march  number: 3000
outputting to json ending with word  midrash  number 600
Outputted json in 0.35 seconds
outputting to json ending with word  napoleon  number 700
Outputted json in 0.36 seconds
outputting to json ending with word  nyaya  number 800
Outputted json in 0.38 seconds
outputting to json ending with word  parvati  number 900
Outputted json in 0.34 seconds
outputting to json ending with word  pistoia  number 1000
Outputted json in 0.37 seconds
outputting to json ending with word  rapa nui  number 1100
Outputted json in 0.51 seconds
current word: reynold  number: 4000
outputting to json ending with word  sabbathless  number 1200
Outputted json in 0.68 seconds
outputting to json ending with word  septuagint  number 1300
Outputted json in 0.65 seconds
outputting to json ending with word  sofia  number 1400
Outputted json in 0.64 seconds
outputting to json ending with word  tammuz  number 1500
Outputted json in 0.66 seconds
outputting to json ending with word  titan  number 1600
Outputted json in 0.71 seconds
outputting to json ending with word  vatican city  number 1700
Outputted json in 0.65 seconds
current word: walpolean  number: 5000
outputting to json ending with word  xenophon  number 1800
Outputted json in 0.64 seconds
current word: acinar  number: 6000
current word: air  number: 7000
current word: angularly  number: 8000
outputting to json ending with word  antiheroism  number 1900
Outputted json in 0.40 seconds
current word: antimechanistic  number: 9000
current word: apronlike  number: 10000
current word: atspring  number: 11000
current word: bairam  number: 12000
current word: befrill  number: 13000
current word: bimbo  number: 14000
current word: bluffy  number: 15000
current word: bronchoscopy  number: 16000
current word: canonship  number: 17000
current word: chaise  number: 18000
current word: circinate  number: 19000
current word: coinverse  number: 20000
current word: conspectus  number: 21000
current word: counterquestion  number: 22000
outputting to json ending with word  creditor  number 2000
Outputted json in 0.48 seconds
current word: cumskin  number: 23000
outputting to json ending with word  curialism  number 2100
Outputted json in 0.34 seconds
outputting to json ending with word  dealate  number 2200
Outputted json in 0.30 seconds
current word: debasement  number: 24000
current word: deprehend  number: 25000
outputting to json ending with word  detusk  number 2300
Outputted json in 0.39 seconds
current word: dipperful  number: 26000
outputting to json ending with word  doctorhood  number 2400
Outputted json in 0.35 seconds
current word: dod  number: 27000
outputting to json ending with word  ducat  number 2500
Outputted json in 0.41 seconds
current word: d√©butante  number: 28000
outputting to json ending with word  egolike  number 2600
Outputted json in 0.40 seconds
current word: elm  number: 29000
outputting to json ending with word  endosphere  number 2700
Outputted json in 0.35 seconds
current word: epiphonema  number: 30000
outputting to json ending with word  essence  number 2800
Outputted json in 0.38 seconds
current word: expertise  number: 31000
outputting to json ending with word  fanger  number 2900
Outputted json in 0.37 seconds
current word: femifascist  number: 32000
outputting to json ending with word  finfolk  number 3000
Outputted json in 0.38 seconds
current word: fluorohydride  number: 33000
outputting to json ending with word  fogbank  number 3100
Outputted json in 0.36 seconds
outputting to json ending with word  fortis  number 3200
Outputted json in 0.35 seconds
current word: freehood  number: 34000
outputting to json ending with word  fruitcake  number 3300
Outputted json in 0.41 seconds
outputting to json ending with word  garrigue  number 3400
Outputted json in 0.32 seconds
current word: gelidity  number: 35000
outputting to json ending with word  glory  number 3500
Outputted json in 0.65 seconds
current word: goom  number: 36000
outputting to json ending with word  gravely  number 3600
Outputted json in 0.66 seconds
current word: haidingerite  number: 37000
outputting to json ending with word  handcloth  number 3700
Outputted json in 0.31 seconds
current word: hemostasis  number: 38000
outputting to json ending with word  hextree  number 3800
Outputted json in 0.70 seconds
current word: hopefulness  number: 39000
outputting to json ending with word  hopium  number 3900
Outputted json in 0.66 seconds
outputting to json ending with word  hydrophobia  number 4000
Outputted json in 0.67 seconds
current word: hypersilyl  number: 40000
outputting to json ending with word  iguana  number 4100
Outputted json in 0.65 seconds
current word: impostorship  number: 41000
outputting to json ending with word  inelegant  number 4200
Outputted json in 0.70 seconds
current word: ingustable  number: 42000
outputting to json ending with word  intercave  number 4300
Outputted json in 0.66 seconds
current word: intersperse  number: 43000
outputting to json ending with word  invillaged  number 4400
Outputted json in 0.68 seconds
current word: jamaicine  number: 44000
outputting to json ending with word  kgotla  number 4500
Outputted json in 0.32 seconds
current word: knifemaking  number: 45000
outputting to json ending with word  laminitis  number 4600
Outputted json in 0.40 seconds
outputting to json ending with word  leg  number 4700
Outputted json in 0.34 seconds
current word: lemuroid  number: 46000
outputting to json ending with word  litherness  number 4800
Outputted json in 0.33 seconds
current word: lordy  number: 47000
outputting to json ending with word  lover  number 4900
Outputted json in 0.36 seconds
outputting to json ending with word  maker  number 5000
Outputted json in 0.34 seconds
current word: manifold  number: 48000
outputting to json ending with word  mariner  number 5100
Outputted json in 0.32 seconds
outputting to json ending with word  megastudio  number 5200
Outputted json in 0.41 seconds
current word: mentorship  number: 49000
outputting to json ending with word  microdose  number 5300
Outputted json in 0.39 seconds
current word: midcalf  number: 50000
outputting to json ending with word  minihelix  number 5400
Outputted json in 0.31 seconds
current word: mis√®re  number: 51000
outputting to json ending with word  mokoro  number 5500
Outputted json in 0.36 seconds
outputting to json ending with word  mouthcare  number 5600
Outputted json in 0.34 seconds
current word: multibaric  number: 52000
outputting to json ending with word  multipool  number 5700
Outputted json in 0.32 seconds
current word: myotasis  number: 53000
outputting to json ending with word  nahualism  number 5800
Outputted json in 0.37 seconds
outputting to json ending with word  nestless  number 5900
Outputted json in 0.31 seconds
current word: neuroparalysis  number: 54000
outputting to json ending with word  nitre  number 6000
Outputted json in 0.41 seconds
current word: nonbillable  number: 55000
outputting to json ending with word  nonconsensual  number 6100
Outputted json in 0.36 seconds
current word: nondesignated  number: 56000
current word: nonhanging  number: 57000
outputting to json ending with word  nonmajor  number 6200
Outputted json in 0.37 seconds
current word: nonmutual  number: 58000
current word: nonrenewed  number: 59000
outputting to json ending with word  nonromantic  number 6300
Outputted json in 0.31 seconds
current word: nontrespasser  number: 60000
outputting to json ending with word  northland  number 6400
Outputted json in 0.34 seconds
current word: octaeteris  number: 61000
outputting to json ending with word  of  number 6500
Outputted json in 0.36 seconds
outputting to json ending with word  oracle  number 6600

Outputted json in 0.41 seconds
current word: ostracism  number: 62000
outputting to json ending with word  overboldness  number 6700
Outputted json in 0.35 seconds
current word: overprompt  number: 63000
outputting to json ending with word  paellalike  number 6800
Outputted json in 0.73 seconds
current word: paragnathous  number: 64000
outputting to json ending with word  parapetted  number 6900
Outputted json in 0.46 seconds
outputting to json ending with word  pause  number 7000
Outputted json in 0.44 seconds
current word: percent  number: 65000
outputting to json ending with word  photomeson  number 7100
Outputted json in 0.38 seconds
current word: phytopigment  number: 66000
outputting to json ending with word  placeless  number 7200
Outputted json in 0.50 seconds
current word: pointerlike  number: 67000
outputting to json ending with word  poisonous  number 7300
Outputted json in 0.56 seconds
outputting to json ending with word  posteriormost  number 7400
Outputted json in 0.67 seconds
current word: potlid  number: 68000
outputting to json ending with word  prehospital  number 7500
Outputted json in 0.33 seconds
current word: pressiometer  number: 69000
outputting to json ending with word  procerus  number 7600
Outputted json in 0.33 seconds
current word: pr√¶senteth  number: 70000
outputting to json ending with word  pseudovector  number 7700
Outputted json in 0.33 seconds
current word: quasidominant  number: 71000
outputting to json ending with word  queerbait  number 7800
Outputted json in 0.36 seconds
outputting to json ending with word  rapism  number 7900
Outputted json in 0.34 seconds
current word: reassimilation  number: 72000
outputting to json ending with word  reengrave  number 8000
Outputted json in 0.65 seconds
current word: relationlike  number: 73000
outputting to json ending with word  resmelt  number 8100
Outputted json in 0.67 seconds
current word: retrotranscript  number: 74000
outputting to json ending with word  robemaking  number 8200
Outputted json in 0.78 seconds
current word: rushlight  number: 75000
outputting to json ending with word  sabre  number 8300
Outputted json in 0.63 seconds
outputting to json ending with word  sanctuary  number 8400
Outputted json in 0.28 seconds
outputting to json ending with word  scenester  number 8500
Outputted json in 0.73 seconds
current word: scolopendra  number: 76000
outputting to json ending with word  semen  number 8600
Outputted json in 1.01 seconds
current word: septically  number: 77000
outputting to json ending with word  sessionless  number 8700
Outputted json in 0.35 seconds
current word: sicklepod  number: 78000
outputting to json ending with word  signature  number 8800
Outputted json in 0.38 seconds
outputting to json ending with word  sleepwalk  number 8900
Outputted json in 0.63 seconds
current word: smotheringly  number: 79000
outputting to json ending with word  soign√©e  number 9000
Outputted json in 1.00 seconds
outputting to json ending with word  spatha  number 9100
Outputted json in 0.29 seconds
current word: speedread  number: 80000
outputting to json ending with word  statusless  number 9200
Outputted json in 0.35 seconds
current word: stentor  number: 81000
outputting to json ending with word  stringer  number 9300
Outputted json in 0.29 seconds
current word: subdwarf  number: 82000
outputting to json ending with word  subsense  number 9400
Outputted json in 0.33 seconds
current word: supercatenoid  number: 83000
outputting to json ending with word  superiorness  number 9500
Outputted json in 0.39 seconds
current word: svarita  number: 84000
outputting to json ending with word  sweetbox  number 9600
Outputted json in 0.35 seconds
outputting to json ending with word  tarot  number 9700
Outputted json in 0.38 seconds
current word: telecipher  number: 85000
outputting to json ending with word  testamur  number 9800
Outputted json in 0.37 seconds
current word: thoughtfully  number: 86000
outputting to json ending with word  thoughtworthy  number 9900
Outputted json in 0.41 seconds
outputting to json ending with word  toolbox  number 10000
Outputted json in 0.37 seconds
current word: traditionalness  number: 87000
outputting to json ending with word  transtemporal  number 10100
Outputted json in 0.44 seconds
outputting to json ending with word  trombonist  number 10200
Outputted json in 0.41 seconds
current word: trustable  number: 88000
outputting to json ending with word  ultraelegant  number 10300
Outputted json in 0.32 seconds
current word: unanthropomorphized  number: 89000
current word: undefinedly  number: 90000
outputting to json ending with word  underbody  number 10400
Outputted json in 0.36 seconds
current word: unfence  number: 91000
outputting to json ending with word  unlovable  number 10500
Outputted json in 0.40 seconds
current word: unlysed  number: 92000
current word: unrenamable  number: 93000
outputting to json ending with word  unspaceworthy  number 10600
Outputted json in 0.37 seconds
current word: untranslatability  number: 94000
outputting to json ending with word  valentineless  number 10700
Outputted json in 0.35 seconds
current word: velvetbreast  number: 95000
outputting to json ending with word  viceman  number 10800
Outputted json in 0.36 seconds
outputting to json ending with word  volumizer  number 10900
Outputted json in 0.40 seconds
current word: warily  number: 96000
outputting to json ending with word  wavetable  number 11000
Outputted json in 0.36 seconds
current word: wis  number: 97000
outputting to json ending with word  wolfkin  number 11100
Outputted json in 0.39 seconds
outputting to json ending with word  yarnlike  number 11200
Outputted json in 0.36 seconds
current word: zeitgeber  number: 98000

In [142]:
english_df['origin'] = english_df['word'].apply(lambda x: word_dict[x])

In [146]:
final_df = copy.deepcopy(english_df)
final_df = final_df.drop_duplicates('word',keep='first')
final_df.tail()

                word word_language related_word related_word_language origin
1338098    zymolysis           eng       -lysis                   eng   None
1338111  zymoplastic           eng      plastic                   eng    lat
1338120   zymosterol           eng       sterol                   eng   None
1338133      zymurgy           eng        -urgy                   eng    grc
1338142       zythum           eng       zythum                   lat    lat

In [382]:
codes = pd.read_csv('language-codes-full_csv.csv')
#codes.columns = ['origin', 'two', 'full_name']
codes = codes.iloc[:, [0,3]]
codes.columns = ['origin', 'full_name']
codes.head()

  origin  full_name
0    aar       Afar
1    abk  Abkhazian
2    ace   Achinese
3    ach      Acoli
4    ada    Adangme

In [383]:
final_df = final_df.merge(codes, on='origin', how='left')

In [391]:
final_df[pd.notnull(final_df['full_name'])]

,word,word_language,related_word,related_word_language,origin,full_name
4,aarhus,eng,Aarhus,dan,dan,Danish
7,aashaadha,eng,‡§Ü‡§∑‡§æ‡§¢,san,san,Sanskrit
8,ab,eng,jb,egy,egy,Egyptian (Ancient)
9,ababil,eng,ÿ£ÿ®ÿßÿ®ŸäŸÑ,ara,ara,Arabic
10,abbas,eng,ÿπÿ®ÿßÿ≥,ara,ara,Arabic
...,...,...,...,...,...,...
98247,zygotic,eng,-ic,eng,grc,"Greek, Ancient (to 1453)"
98248,zyme,eng,Œ∂œçŒºŒ∑,grc,grc,"Greek, Ancient (to 1453)"
98255,zymoplastic,eng,plastic,eng,lat,Latin
98257,zymurgy,eng,-urgy,eng,grc,"Greek, Ancient (to 1453)"
98258,zythum,eng,zythum,lat,lat,Latin

In [400]:
pivot = pd.pivot_table(data=final_df[pd.notnull(final_df['full_name'])],
        index=['full_name'],
        values=['word'],
        aggfunc='count').reset_index()

In [401]:
pivot.to_csv('language_list.csv')

In [404]:
grouping = pd.read_csv('test.csv')
grouping.head()

                     full_name    Group
0  English; Middle (1100-1500)  English
1                        Latin    Latin
2   English; Old (ca.450-1100)  English
3    French; Old (842-ca.1400)    Latin
4     Greek; Ancient (to 1453)    Greek

In [405]:
final_df = final_df.merge(grouping, on='full_name', how='left')

In [410]:
language_df = final_df.loc[pd.notnull(final_df['origin']), ['word', 'origin', 'full_name', 'Group']]

In [438]:
pivot = pd.pivot_table(data=language_df[pd.isnull(language_df['full_name'])],
               index='origin',
               values=['word'],
               aggfunc='count').reset_index().sort_values('word', ascending=False)

In [439]:
pivot[pivot['word'] > 10]

   origin  word
15    cym    40
32    isl    26
44    mri    23
12    bod    20
23    gml    20
34    kat    20
76    yue    17
26    hbs    13

In [419]:
language_df.loc[language_df['origin'] == 'fra','full_name'] = 'French'
language_df.loc[language_df['origin'] == 'fra','Group'] = 'Latin'

In [420]:
language_df.loc[language_df['origin'] == 'deu','full_name'] = 'German'
language_df.loc[language_df['origin'] == 'deu','Group'] = 'Germanic'

In [421]:
language_df.loc[language_df['origin'] == 'nld','full_name'] = 'Dutch;Flemish'
language_df.loc[language_df['origin'] == 'nld','Group'] = 'Germanic'

In [422]:
language_df.loc[language_df['origin'] == 'xno','full_name'] = 'Anglo-Norman'
language_df.loc[language_df['origin'] == 'xno','Group'] = 'Germanic'

In [423]:
language_df.loc[language_df['origin'] == 'msa','full_name'] = 'Malay'
language_df.loc[language_df['origin'] == 'msa','Group'] = 'Other'

In [428]:
language_df.loc[language_df['origin'] == 'fas','full_name'] = 'Persian'
language_df.loc[language_df['origin'] == 'fas','Group'] = 'Other'

In [429]:
language_df.loc[language_df['origin'] == 'hye','full_name'] = 'Armenian'
language_df.loc[language_df['origin'] == 'hye','Group'] = 'Other'

In [436]:
language_df.loc[language_df['origin'] == 'cmn','full_name'] = 'Mandarin Chinese'
language_df.loc[language_df['origin'] == 'cmn','Group'] = 'Other'

In [437]:
language_df.loc[language_df['origin'] == 'ell','full_name'] = 'Modern Greek'
language_df.loc[language_df['origin'] == 'ell','Group'] = 'Other'

In [440]:
language_df.to_csv('language_data.csv')